if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export PATH="$HOME/bin:/usr/local/bin:$PATH"

export EDITOR="nvim"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
